name: Node.js CI

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        name: cache node_nodules
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Node Modules
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn
      - name: Lint
        run: yarn lint:ci
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        name: cache node_nodules
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Node Modules
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn
      - name: Test
        run: yarn test
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        name: cache node_nodules
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Node Modules
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn
      - name: Build
        run: yarn build
